myproject/inscripciones/urls.py
from django.urls import path
from . import views



app_name = 'inscripciones'

urlpatterns = [
    path('inscripcion_tertulia', views.inscripcion_tertulia, name="inscripcion_tertulia"),

    path('activate/<uidb64>/<token>/', views.activate, name="activate"),

      path('welcome_tertulia_page/', views.welcome_tertulia_page, name='welcome_tertulia_page'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about),
    path('cursos/', include('cursos.urls')),
    path('users/', include('users.urls')),
    path('tertulias/', include('tertulias.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    #path('inscripciones/', include('inscripciones.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/tertulias/urls.py
from django.urls import path
from . import views

app_name = 'tertulias'

urlpatterns = [
    path('', views.tertulias_list, name="list"),
]

myproject/users/urls.py
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('contacto/', views.contacto, name='contacto'),

    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
  
    


]

myproject/inscripciones/models.py
from django.db import models
from users.models import User
from tertulias.models import Tertulia


class TertuliaForm(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True, default=None)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    tertulia_name = models.ForeignKey(Tertulia, on_delete=models.CASCADE, default=None)
    tertulia_folio_id =models.IntegerField()



    def __str__(self):
        return self.email
    

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    tertulia_name = models.ForeignKey(Tertulia, on_delete=models.DO_NOTHING, default=False, null=False)
    tertulia_folio_id =models.IntegerField()


    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.last_name} {self.first_name}'

    def __str__(self):
        return self.email

myproject/inscripciones/forms.py
from django import forms
from .models import Student


class TertuliaRegistro(forms.ModelForm):
    class Meta:
        model = Student
        fields = [ 'last_name','first_name', 'email', 'phone_number', 'tertulia_name', 'tertulia_folio_id']

myproject/inscripciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator

from tertulias.models import Tertulia
from .models import User
from .models import Student
from .forms import TertuliaRegistro
from django.contrib import messages
from .utils import send_verification_email
from django.utils.http import urlsafe_base64_decode



@login_required(login_url="/users/login/")
def inscripcion_tertulia(request):
        
        if request.method == 'POST':
           
            form = TertuliaRegistro(request.POST)
            if form.is_valid():

                user = request.user
                first_name = form.cleaned_data['first_name']
                
                last_name = form.cleaned_data['last_name']

                #request.session['last_name'] = last_name
                
                #username = form.cleaned_data['username']
                
                phone_number = form.cleaned_data['phone_number']

                tertulia_name = form.cleaned_data['tertulia_name']
                tertulia_folio_id = form.cleaned_data['tertulia_folio_id']

                

                email = form.cleaned_data['email']


                

                student = Student.objects.create(first_name=first_name, last_name=last_name, phone_number=phone_number, email=email, tertulia_name = tertulia_name, tertulia_folio_id=tertulia_folio_id )
                
                

                student.save()
                print(student)
                print(student.last_name)
                print(user)



                send_verification_email(request, user)
                messages.success(request, 'Te enviamos un correo de verificacion a tu correo electrónico para que puedas continuar con tu proceso de inscripcion!')
                return redirect('home')
            else:
                print('Invalid form')

        else:
            form = TertuliaRegistro()
        context = {
            'form': form,
        }

        return render(request, 'inscripciones/tertulias_registro.html', context)


def activate(request, uidb64, token):
    #Activate the inscription by setting the is_active status to True
    try:
         uid = urlsafe_base64_decode(uidb64).decode()
         user = User._default_manager.get(pk=uid)
         request.session['uid']  = uid
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
         user = None

    if user is not None and default_token_generator.check_token(user, token):
         user.is_active = True
         user.save()
         messages.success(request, 'Felicidades, ya tienes un lugar reservado en la Tertulia.')
         return redirect('inscripciones:welcome_tertulia_page')
    else:
         messages.error(request, 'Invalide activation link')
         return redirect('home')
    

def welcome_tertulia_page(request):
    pk = request.session.get('uid')
    user = User.objects.get(pk=pk)
    user_email = user.email
    
    student = Student.objects.filter(email=user_email).first()


    student_id = student.id
    student_first_name = student.first_name
    student_last_name = student.last_name
    student_tertulia_name = student.tertulia_name
    student_tertulia_folio_id = student.tertulia_folio_id
    print(student_tertulia_name)


    tertulia = Tertulia.objects.get(tertulia_name=student.tertulia_name)
    print(tertulia)

    tertulia.tertulia_lugares -= 1
    tertulia.save()



    #return tertulia.tertulia_lugares
    #print(tertulia.tertulia_lugares)
   

         
    

    
    


 

    context = {
        'student_id': student_id,
        'student_first_name': student_first_name,
        'student_last_name':  student_last_name,
        'student_tertulia_name': student_tertulia_name,
        'student_tertulia_folio_id': student_tertulia_folio_id,

    }

    return render(request, 'inscripciones/welcome_tertulia_page.html', context)
    


    


         



myproject/inscripciones/templates/inscripciones/tertulias_registro.html
{% extends 'layout.html'%}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                    <h4 class="text-center" style="margin-bottom: 0;">Bienvenidos literatus</h4>
                    <p >Favor de rellenar esta forma para inscribirse en la tertulia de tu elección. Es IMPORTANTE que el nombre de la tertulia coincida con el número de folio de la tertulia.</p>
                    <hr>
                    <div id="restaurant-sets-holder">
                        <form action="{% url 'inscripciones:inscripcion_tertulia' %} "class="form-fields-set foodbakery-dev-restaurant-form" method="post">
                            {% csrf_token %}
                            <ul class="register-add-restaurant-tab-container restaurant-information-tab-container">
                                <li>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="row">
                                                <ul >
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Nombre</label>{{ form.first_name }}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Apellido(s)</label>{{ form.last_name }}
                                                            </div>
                                                        </div>

                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Email</label>{{ form.email }}
                                                            </div>
                                                        </div>
                                                       
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Número de Teléfono</label>{{ form.phone_number }}
                                                            </div>
                                                        </div>
                                                        
                                                    </li>
                                                    
                                                    <li>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Nombre de la tertulia</label>{{ form.tertulia_name }}
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                            <div class="field-holder">
                                                                <label>Tertulia folio id</label>{{ form.tertulia_folio_id }}
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                   
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="field-holder">
                                                <div class="payment-holder">
                                                    <input type="submit" value="Continuar" id="btn-next-restaurant-information" class="bgcolor">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">

                                    </div>
                                </li>
                            </ul>
                            
                        </form>
                    </div>
                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->
{% endblock  %}

myproject/inscripciones/templates/inscripciones/welcome_tertulia_page.html
{% extends 'layout.html'%}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="user-dashboard loader-holder" style="width: 450px; min-hight: auto;">
                        <div class="user-holder">
                            
                    <h4 class="text-center" style="margin-bottom: 0;">Tertulias Literarias Sábatinas</h4>
                    <br>
                    <p>"Porque a los ratones de biblioteca también nos gusta el queso"...</p>
                    <hr>
                    <br>
                    <h4>Hola, <strong>{{ student_first_name }}</strong></h4>
                    <br>  
                     <p>Te damos la bienvenida a la tertulia literaría sábatina: <strong>{{ student_tertulia_name }}</strong></p>
                     <br>
                     <p>Tertulia con el numero de folio: {{ student_tertulia_folio_id }}</p>
                     <br>      
                    {% if student_tertulia_folio_id == 1 %}
                    <p>No reuniremos en la cafetería La Borra del Café ubicada sobre Avenida Chapultepec sur # 208, Guadalajara </p>
                    <p>La hora y fecha de inicio es el día sábado 21 de diciembre a las 7:30pm</p>
                    <p>Literatus encargada: <strong>María Ines </strong> </p>
                    <br>
                    <p><strong>No olvides traer tu libro.</strong></p>
                    {% elif student_tertulia_folio_id == 2 %}
                    <p>Nos reuniremos en Café Revolución, ubicado en: Av. Revolución 1905, Tizapán San Ángel, San Ángel, Álvaro Obregón, 01000 Ciudad de México, CDMX</p>
                    <p>La hora y fecha de inicio es el día sábado 30 de noviembre a las 7:00pm</p>
                    <p>Literatus encargada: <strong>Alejandra </strong> </p>
                    <br>
                    <p><strong>No olvides traer tu libro.</strong></p>
                    {% elif student_tertulia_folio_id == 3 %}
                    <p>Nos reuniremos en Pasión Café, ubicado en Perif. Blvd. Manuel Ávila Camacho 3228 Boulevares 53100, Boulevares, 53140 Naucalpan de Juárez, Méx. </p>
                    <p>La hora y fecha de inicio es el día sábado 30 de noviembre a las 6:30pm</p>
                    <p>Literatus encargado: <strong>Alonso </strong> </p>
                    <br>
                    {% elif student_tertulia_folio_id == 4 %}
                    <p>No reuniremos en la cafetería del Péndulo, ubicada en: Av. Álvaro Obregón 86, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX</p>
                    <p>La hora y fecha de inicio es el día sábado 21 de noviembre a las 8:00pm</p>
                    <p>Literatus encargado: <strong>Xavier </strong> </p>
                    <br>
                    {% elif student_tertulia_folio_id == 5 %}
                    <p>No reuniremos en la cafetería del Péndulo, ubicada en: Av. Álvaro Obregón 86, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX</p>
                    <p>La hora y fecha de inicio es el día sábado 21 de diciembre a las 6:00pm</p>
                    <p>Literatus encargado: <strong>Xavier </strong> </p>
                    <br>
                    
                    {% else %}
                    <h2>Ninguna Tertulia con este número de folio</h2>
                    <br></br>
                    {% endif %}
                    <p>Si tienes alguna duda o comentario que quieras hacernos llegar, contáctanos directamente a nuestro correo electrónico.</p>
                    <p>Si por algun motivo deseas cancelar tu participación; por favor avisanos con anticipación para poner éste lugar disponible.</p>
                    <br>
                    <p>Por favor tómale una fotografía con tu celular a esta pantalla para que tengas siempre los datos a la mano.</p>
                    <br>
                    <p><strong>No olvides traer un ejemplar del libro en cuestión.</strong></p>
                    <br>
                    <a href="{% url 'tertulias:list' %}" class="btn btn-success">Ir a la página principal</a>


                </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Main Section End -->
{% endblock  %}