myproject/cursos/urls.py
from django.urls import path
from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos_list, name="lista"),
    path('<slug:slug>', views.curso_page, name="page"),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about),
    path('cursos/', include('cursos.urls')),
    path('users/', include('users.urls')),
    path('tertulias/', include('tertulias.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    #path('inscripciones/', include('inscripciones.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/tertulias/urls.py
from django.urls import path
from . import views

app_name = 'tertulias'

urlpatterns = [
    path('', views.tertulias_list, name="list"),
]

myproject/users/urls.py
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('contacto/', views.contacto, name='contacto'),

    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
  
    


]

myproject/templates/home.html

{% extends "layout.html" %}

{% block title %}

{% endblock  %}

{% block content  %}

<!-- Hero Section -->
 <section id="hero" class="hero section">



    <div class="container">
      <div class="row justify-content-center" data-aos="zoom-out">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1 class="titulo-club-2 text-white">¿Quiénes somos?</h1>
          <p class=" titulo-par-1"><span class="logo">Literatus</span>: <a href="about/"><small class="small-titulo">Club de lectura</small></a>  <a class="link-titulo" href="/cursos/">Talleres y Cursos</a></p></br>
        </div>
        
        <p class="text-white parrafo-club">Nos reunimos por los cuatro puntos cardinales; con la misión de organizar tertulias literarias sabatinas, donde comentamos el mismo libro que nos apasiona a todos los concurrentes a la tertulia. Las Tertulias Literarias Sabatinas son coordinadas por el asesor literartio de la zona; ya que él o ella son quienes tienen cierta autoridad en la materia y conocimientos profundos de la obra literaría en turno. Si te gustaría unirtenos, conoce si hay algun grupo por reunirse cerca de tu localidad.
          <p class="text-white parrafo-club">Conoce a nuestros literatus y sus localidades:</p>
      </div>

      <div class="row gy-4 mt-5">
        <div class="col-md-6 col-lg-3" data-aos="zoom-out">
          <div class="icon-box">
            <img  class="foto" src="static/assets/img/alejandra.jpg" alt="">

            <h3 class="titulo-docente"> María Alejandra Sántos</h3>
              <p class="parrafo-docente">Egresada de la U.N.A.M. de la Licenciatura en Filosofía y Letras. 
                Actualmente se desempeña cómo correctora de estilo en La Jormada. Ha participado
                en diversos proyectos literarios de corte informativo para diferentes entidades en
                la web. Así también se desempeñó como articulista de tiempo completo para la revista <strong>Algarabía</strong>
                en la Ciudad de México.</p>
                <h2 class="tertulias-literarias">Tertulias<span class="literatus-tertulias">literarias</span>Sábatinas</h2>
                <p class="parrafo-docente">También es la literata encargada de coordinar la próxima tertulia sábatina de <strong  class="zona-tertulia">la zona sur de la Ciudad de México</strong> </p></br>
                <span></span><a class="btn btn-primary" href="{% url 'tertulias:list' %}">Informes</a>


                
          </div>
        </div><!--End Icon Box -->

        <div class="col-md-6 col-lg-3" data-aos="zoom-out">
          <div class="icon-box">

              <img  class="foto" src="static/assets/img/alonso.jpg" alt="">

              <h3 class="titulo-docente"> Alonso Trejo Torres</h3>
              <p class="parrafo-docente">Curso la carrera de Comunicación visual en La Universidad de la Comunicación. 
              Colaboró como columnista en Univision.com en la sección de deportes, especializandose en escribir artículos sobre la liga mexicana de futbol y sus protagonistas. <br>
                <h2 class="tertulias-literarias">Tertulias<span class="literatus-tertulias">literarias</span>Sábatinas</h2>
                <p class="parrafo-docente">También es el literato encargado de coordinar la próxima tertulia sábatina de <strong  class="zona-tertulia">la zona norte de la Ciudad de México</strong></p></br>
                <span></span><a class="btn btn-primary" href="{% url 'tertulias:list' %}">Informes</a>


          </div>
        </div><!--End Icon Box -->

        <div class="col-md-6 col-lg-3" data-aos="zoom-out">
          <div class="icon-box">
            <img  class="foto" src="static/assets/img/maria-1.jpg" alt="">
            
            <h3 class="titulo-docente"> Inés Soraya Martínez</h3>
              <p class="parrafo-docente">Licenciada en Ciencias de la Comunicación y Medios Digitales, por parte de la Universidad de Guadalajara(UDG). 
                Orgullosamente tapatia, ha desarrollado su carrera en el medio televisivo de Guadalajara, comenzando su trayecto profesional como "jala cables"  en UDG TV donde despúes asendió a asistente de producción. Ahora trabaja como freelance para algunas productoras en aquella ciudad. <br>
                <h2 class="tertulias-literarias">Tertulias<span class="literatus-tertulias">literarias</span>Sábatinas</h2>
                <p class="parrafo-docente">También el la literata encargada de coordinar la próxima tertulia sábatina de <strong class="zona-tertulia">la zona centro de Guadalajara</strong></p></br>

                <span></span><a class="btn btn-primary" href="{% url 'tertulias:list' %}">Informes</a>
          </div>
        </div><!--End Icon Box -->

        <div class="col-md-6 col-lg-3" data-aos="zoom-out">
          <div class="icon-box">
            <img  class="foto" src="static/assets/img/panito-3.jpg" alt="">
            <h3 class="titulo-docente"> Xavier Pano Segura</h3>
              <p class="parrafo-docente">Curso la Licenciatura de Administracion en la facultad de la U.N.A.M. 
                Su inquietud por la escritura lo llevó a amistarse mediante este vínculo con Hugo Torres, cineasta egresado de la Escuela Nacional de Artes Cinematográficas (ENAC) y con quien participó en la realización de varios guiones de cortometrajes y algunos anuncios de radio.  <br>
                <h2 class="tertulias-literarias">Tertulias<span class="literatus-tertulias">literarias</span>Sábatinas</h2>
                <p class="parrafo-docente">También es el literato encargado de coordinar la próxima tertulia sábatina de <strong class="zona-tertulia">la zona centro de la Ciudad de México</strong> </p></br>
                <span></span><a class="btn btn-primary" href="{% url 'tertulias:list' %}">Informes</a>
          </div>
        </div><!--End Icon Box -->


      </div>
    </div>
   
    
  </section><!-- /Hero Section -->

{% endblock  %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

      
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Proyecto Literatus
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href={% static 'assets/css/style.css' %} />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    
    <link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">

    <script src="{% static 'assets/js/main.js' %}" defer></script>
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.7/dist/cdn.min.js"></script>
</head>
<body>
    <header id="header" class="header d-flex align-items-center sticky-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center">
    
          <a href="#" class="d-flex align-items-center me-auto">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1 class="logo">Literatus</h1>
          </a>
    
          <nav id="navmenu" class="navmenu">
            <ul>
              <li><a class=" {% if request.resolver_match.url_name == 'home' %}active {% endif %}" href="/">Home<br></a></li>
              <li>
                <a class=" {% if request.resolver_match.url_name == 'list' %}active {% endif %}" href="{% url 'tertulias:list' %}" >Club de Lectura<span class="separador">&</span><span class="tertulia-navbar">TertuliasSabatinas</span></a>
              </li>
              <li><a href="{% url 'cursos:lista' %}" class="nav-link {% if request.resolver_match.url_name == 'lista' %}active {% endif %}">Cursos y Talleres</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'users:logout' %}" class="nav-link {% if request.resolver_match.url_name == 'logout' %}active {% endif %}">Logout</a></li>
              
              {% else %}
              <li><a href="{% url 'users:login' %}" class="nav-link {% if request.resolver_match.url_name == 'login' %}active {% endif %}">Log in</a></li>
             <li><a href="{% url 'users:register'%}" class="nav-link {% if request.resolver_match.url_name == 'register' %}active {% endif %}">Registrate</a></li>
             
             {% endif %}
             <li><a href="{% url 'users:contacto' %}" class="nav-link {% if request.resolver_match.url_name == 'contacto' %}active {% endif %}" >Contacto</a></li>
            </ul>
            
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
          </nav>
          <section class="messages" id="messages">
            {% include 'includes/toast.html' %}
          </section>
        </div>
    </header>

    <!--
    <nav>
        <a href="/">Home</a>
        <a href="/about">About</a>
        <a href="/cursos">Cursos</a>
    </nav>
    -->
    <main>

        {% block content %}

        {% endblock  %}

        
    </main>

     

  <!-- Preloader -->


  <!-- Vendor JS Files -->
 

  <!-- Main JS File -->
   
  <script src="assets/js/main.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>